pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
               sh 'pwd'
               sh 'cd /usr/share/nginx/html/stage && pwd && git pull'
            }
        }
     stage('Deliver') {
            steps {
                sh 'echo "Changes Deployed"'
            }
        }
    }
}
