pipeline {
    
    stages {
        stage('Build') {
            steps {
               sh 'cd /var/www/html/ && git stash && git pull'
            }
        }
     stage('Deliver') {
            steps {
                sh 'echo "Changes Deployed"'
            }
        }
    }
}
